name: Release test

# Note: This workflow does not build for releases. It attempts to build release binaries daily to ensure the repo
# is in a good state.

on: workflow_dispatch

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  weekly-test-release:
    name: Test release
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.3, release-1.2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag=v3.3.0
        with:
          ref: ${{ matrix.branch }}
      - name: set fake tag
        run: |
          git tag fake-tag
      - name: Set env
        run:  echo "RELEASE_TAG=fake-tag" >> $GITHUB_ENV
      - name: build release binaries
        run: |
          make release